[package]
name = "commit-check-core"
version = "0.1.0"
authors = ["LNSD <lnsdev@proton.me>"]
edition = "2021"
rust-version = "1.56.1"
license = "Apache-2.0"

[dependencies]
thiserror.workspace = true

[dev-dependencies]
assert_matches = "1.5.0"
