name: ci
on:
  pull_request:
  merge_group:
  push:
    branches:
    - "main"
    - "renovate/lock-file-maintenance"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy, llvm-tools-preview

      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@c7e8aa40ae2c975774d3bd766beb92927cfd7771 # v1

      - name: Install Cargo LLVM cov
        uses: baptiste0928/cargo-install@94e1849646e5797d0c8b34d8e525124ae9ae1d86 # v3
        with:
          crate: cargo-llvm-cov

      - name: Install Cargo nextest
        uses: baptiste0928/cargo-install@94e1849646e5797d0c8b34d8e525124ae9ae1d86 # v3
        with:
          crate: cargo-nextest
          version: 0.9.66

      - name: Setup Rust problem matchers
        uses: r7kamura/rust-problem-matchers@2c2f1016021a7455a6b5b4bbae31145f3b3cd83a # v1

      - name: Cargo check
        run: cargo check --all-targets --all-features

      - name: Cargo fmt
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings --force-warn deprecated --force-warn dead-code

      - name: Cargo doc
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --no-deps --all-features

      - name: Run unit tests
        run: cargo llvm-cov nextest --lib --lcov --output-path unit-lcov.info

      - name: Run integration tests
        run: cargo llvm-cov nextest --test '*' --lcov --output-path it-lcov.info

      - name: Upload unit tests coverage report to codecov
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4
        with:
          files: unit-lcov.info
          flags: unit

      - name: Upload integration tests coverage report to codecov
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4
        with:
          files: it-lcov.info
          flags: integration
